### ISSUE TITLE
Random Extra Goto(Unknown=X)'s

### ISSUE THREAD

**Issue by abyssalx** [Sammi-Husky/Sm4sh-Tools#35]
Something I noticed when diffing my Ganon mod with the original data is that under GFX, sometimes the changed file has an extra Goto() thing. If it said something like `Goto(Unknown=-81)` or something, the next line would be again `Goto(Unknown=-81)`. I'm not sure if this actually causes any issues though, it's just something I thought I should mention.

Edit: forgot to mention sometimes there would be 2 extras. probably from compiling and then recompiling.

**Comment by Rosscalvinar** [comment]
I have had the same problem editing lucas. It creates a new goto every time I exit and reopen the code for a move. It isn't just happening in GFX, either. When it happens in the main tab, it causes the game to crash. Its making it really annoying to mod. I hope you can fix it soon.
Edit:
I've found that it always happens after brackets{} that end in a goto(Unknown), and that there shouldn't be a goto(Unknown) after the brackets at all.

**Comment by Sammi-Husky** [comment]
Fixed in latest versions
