### ISSUE TITLE
Umm

### ISSUE THREAD

**Issue by SuperMario64fan** [Sammi-Husky/Sm4sh-Tools#40]
Hey, how do I use it? It's just a load of folders and I don't know how to use this! Can you make it easier to use or give me steps to make it usable for someone like me? Just folders and files!

**Comment by ghost** [comment]
What version are you using? Oddly enough, different versions of Sm4shCommand work for different platforms. Like I use 1.3.0 for Wii U, and 1.2.2 for 3DS. A lot of things need to be ironed out afaik.

**Comment by Sammi-Husky** [comment]
You've probably downloaded the source code instead of a release. The releases are on the release page of the repository.
