### ISSUE TITLE
Edited fighter messes up/corrupts when loading them using saltySD (3DS version)

### ISSUE THREAD

**Issue by ghost** [Sammi-Husky/Sm4sh-Tools#42]
Whenever I make an edit or modify any character, strange side effects happen, like all the specials are not working, and certain animations make the character crash the game. 1 in particular, I modded Lucario's taunts for him to transform into Mega Lucario. Some of his taunts, like his down taunt, oddly freeze the game, and idk why. Is this a known bug? Or am I doing something wrong? I am using version 1.2.2 cuz I can't seem to parse any animations or modify anything for 3ds fighters using version 1.3.0. Please let me know soon. Thx. 

I know there are bugs and things are being worked on, but I find this to be a major issue with this. Kinda defeats the purpose of modding Smash 4 characters. :/

**Comment by Sammi-Husky** [comment]
This was only a problem in quite old versions, causing taunts to crash the game and such. Namely, it wasn't rebuilding the field in the ACMD header for cmd count. These issues should be fixed in the nightly build. A little while ago i pushed a change that fixed not being able to parse animations on 3ds

**Comment by ghost** [comment]
ahh. very cool. I will try it out now. :) Also, quick question. Do you know if there is a script or function in animcmd that allows a character to generate an item? I know with Peach with her down special, she generates her own items as well as some generic ones such as bomb ombs and Mr Saturns. If so, would you know if there is an ID list for Generate_Weapon on the internet? Thank you so much. :)

UPDATE: I was able to parse animations for 3ds fighters! :D

**Comment by Sammi-Husky** [comment]
Generate_Weapon is used for spawning articles. Unfortunately i don't believe there is a known spawn item command in ACMD. It might be handled entirely in MSC.
