### ISSUE TITLE
FITC doesn't want to compile

### ISSUE THREAD

**Issue by SUOlivia** [Sammi-Husky/Sm4sh-Tools#48]
when i want to compile a custom moveset using FITC , i have this error:
`Exception non gérée : System.ArgumentOutOfRangeException: startIndex ne peut pas être supérieur à la longueur de la chaîne.
Nom du paramètre : startIndex
   à System.String.Substring(Int32 startIndex, Int32 length)
   à SALT.Scripting.AnimCMD.ACMDCompiler.CompileSingleCommand(String line)
   à SALT.Scripting.AnimCMD.ACMDCompiler.CompileCommands(String[] lines)
   à SALT.Scripting.AnimCMD.ACMDCompiler.Compile(String input)
   à SALT.Scripting.AnimCMD.ACMDCompiler.CompileFile(String filepath)
   à FitCompiler.Program.compile_acmd(String mlist, String output)
   à FitCompiler.Program.Main(String[] args)`
the error is the same when i try with `-le` and `-be`

**Comment by Sammi-Husky** [comment]
This is caused by locale related issues, will be fixed next ver (will force decompilation in us locale).
