### ISSUE TITLE
Still get crash with Ness

### ISSUE THREAD

**Issue by Filuz** [Sammi-Husky/Sm4sh-Tools#69]
Using latest commit 98dd079
No more error when decompiling/compiling, and now using fair won't immediatly crash the game but only a part of the graphic effect play and may crash after.
Other unrelated move also make the game crash like stopping after running or double jump.

**Comment by Sammi-Husky** [comment]
With FITX or SM4SHCommand? Vanilla files or edited?

**Comment by Filuz** [comment]
FITX, didn't try with SM4SHcommand yet. Same results with vanilla files or edited files.

**Comment by Sammi-Husky** [comment]
Can you try again with latest commit? Pushed a commit a while ago that should fix the problem

**Comment by Filuz** [comment]
It works great now!

**Comment by Sammi-Husky** [comment]
Awesome, glad to hear it. I'll close the issue now 👍
