### ISSUE TITLE
Loop compilation error with FITC

### ISSUE THREAD

**Issue by jugeeya** [Sammi-Husky/Sm4sh-Tools#70]
It seems there is another problem with autocalculation, this time with the Goto in loops. It used to work on an older commit, but now something is causing the value to be off by 2. In game, this causes a crash. Once again, left is before compilation, and right is after compilation as viewed in Sm4shCommand.

![image](https://user-images.githubusercontent.com/15069495/28313546-1d2c643c-6b6c-11e7-93d2-60e987c58fb3.png)

**Comment by Sammi-Husky** [comment]
Pushed a few commits that should address this, could you try again with latest commit build?

**Comment by jugeeya** [comment]
Fixed! Tested in game as well.

![image](https://user-images.githubusercontent.com/15069495/28397293-8eedbc48-6cb5-11e7-862f-170d5caacd99.png)
