### ISSUE TITLE
FITD Conditional decompilation problems

### ISSUE THREAD

**Issue by jugeeya** [Sammi-Husky/Sm4sh-Tools#71]
This seems to be a minor issue, but it makes some characters impossible to recompile. What it seems to be is that some conditionals that are empty (probably shouldn't be empty?) add an extra line ("TRUE(Unknown=0x2)"), which causes a problem upon recompilation. The characters are Mewtwo, Villager, and Yoshi, and following are the situations. 

Mewtwo CliffCatch.acm
![image](https://user-images.githubusercontent.com/15069495/28559488-9cc9d602-70cb-11e7-8dea-24043a0001ab.png)

Villager CliffCatch.acm
![image](https://user-images.githubusercontent.com/15069495/28559414-53589f44-70cb-11e7-841d-88b090bb7048.png)

Yoshi 0xF7Fa88CD.acm
![image](https://user-images.githubusercontent.com/15069495/28559361-16bcfcd8-70cb-11e7-8a1b-ad249b841f1b.png)

**Comment by Sammi-Husky** [comment]
Interestingly enough, i don't think this is a bug in the decompilation. The raw commands actually DO specify that this is an empty if statement...

So i think that's intentional weirdly enough. However, the true statement being repeated is definitely a bug. Will try to fix it today

**Comment by Sammi-Husky** [comment]
Should be fixed in afe7080
