### ISSUE TITLE
Compiling a decompiled script removes "." from .acm files. 

### ISSUE THREAD

**Issue by huppfi** [Sammi-Husky/Sm4sh-Tools#73]
If I decompile and recompile the same script FITX removes the dot from Parameters making a 12.2 into a 122 for example. 

[EXAMPLE](https://i.imgur.com/X50v7dE.png)

Left Picture is after Compiling; right Picture is original.

**Comment by LemonatedCat** [comment]
This could be a language issue, works fine atm
